### ISSUE TITLE
Record Limit for Code? 

### ISSUE THREAD

**Issue by cannin** [PritiShaw/Analyze-MESH#5]
No need to fix things, but what are the limits to the code? It looks like more than 200 PMIDs will probably cause an error:

https://www.ncbi.nlm.nih.gov/books/NBK25499/#

What about MTI?

**Comment by PritiShaw** [comment]
I couldnot find any limit mentioned wrt batch MTI(webapi).
In their [Terms of Service](https://ii.nlm.nih.gov/Terms_of_Service.shtml), it is mentioned that, webapi can have **2 active jobs per IP**.
I read in documentation that they advised to send large files instead of breaking in smaller chunks, they take care of parallel processing. If I find the link to this part of documentation I will let you know.

This is an image, you can see that around **175thousand items(abstracts)** are being processed in this particular job.
![image](https://user-images.githubusercontent.com/34039705/99884850-26d1e980-2c57-11eb-8d86-12767aa711e4.png)

**Comment by cannin** [comment]
Thanks. This is sufficient. No need to spend further time on this. Since PubMed API can only handle about 200 IDs at once maybe that is a sufficient upper limit to the chunk size.
